version: '3.1'

services:

  node:
    image: node:10-stretch
    restart: ${DOCKER_RESTART}
    command: ${NODE_COMMAND}
    tty: true
    ports:
      - "${NODE_PORT}:${NODE_PORT}" # host:container
    links:
      - postgres
      - mongo
    working_dir: /shoplistic/server
    environment:
      ADMIN_USERS: ${ADMIN_USERS}
      NODE_PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}
      NODE_LOG_REQUESTS: ${NODE_LOG_REQUESTS}
      NODE_JWT_SECRET: ${NODE_JWT_SECRET}
      NODE_RE_SECRET_KEY: ${NODE_RE_SECRET_KEY}
      PG_USER: ${PG_USER}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_PASSWORD: ${PG_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${SHOPLISTIC_DIR}:/shoplistic/
      - ${SHOPLISTIC_DIR}/../frontend:/frontend/:ro

  postgres:
    image: postgres
    restart: ${DOCKER_RESTART}
    # ports:
    #   - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ${DATA_STORE}/postgres:/var/lib/postgresql/data
      - ${SHOPLISTIC_DIR}/scripts/postgres:/scripts/
      - ${DUMP_DIR}/postgres:/export/

  mongo:
    image: mongo
    restart: ${DOCKER_RESTART}
    # ports:
    #   - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_USER}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${DATA_STORE}/mongo:/data/db
      - ${SHOPLISTIC_DIR}/scripts/mongo:/scripts/
      - ${DUMP_DIR}/mongo:/export/
